exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "package.json",
    "favicon-gen.js",
    ".gitignore",
    "CNAME",
    "scripts",
    "*.sh",
    "README.md"
  ]
